{
 "title": "Azure Service Bus SDK for Java",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Sent, received, and settled message rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_destination) (rate(messaging_servicebus_messages_sent_total{otel_status_code=\"ok\"}[$__rate_interval]))",
     "legendFormat": "sent - {{net_peer_name}}/{{messaging_destination}}"
    },
    {
     "expr": "sum by (net_peer_name, messaging_destination) (rate(messaging_servicebus_receiver_lag_count[$__rate_interval]))",
     "legendFormat": "received - {{net_peer_name}}/{{messaging_destination}}"
    },
    {
     "expr": "sum by (net_peer_name, messaging_destination, messaging_servicebus_disposition_status) (rate(messaging_servicebus_settlement_request_duration_count{otel_status_code=\"ok\"}[$__rate_interval]))",
     "legendFormat": "settled - {{net_peer_name}}/{{messaging_destination}}"
    }
   ]
  },
  {
   "title": "Receiver lag, P95, sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_servicebus_receiver_lag_bucket[$__rate_interval])) by (le, messaging_destination, net_peer_name)) ",
     "legendFormat": "{{net_peer_name}}/{{messaging_destination}}"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 } },
  {
   "title": "Request duration, ms, P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_az_amqp_producer_send_duration_bucket[$__rate_interval])) by (le, amqp_delivery_state, messaging_destination, net_peer_name)) ",
     "legendFormat": "send {{net_peer_name}}/{{messaging_destination}} - {{amqp_delivery_state}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_az_amqp_management_request_duration_bucket[$__rate_interval])) by (le, messaging_destination, net_peer_name)) ",
     "legendFormat": "management {{net_peer_name}}/{{messaging_destination}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_servicebus_settlement_request_duration_bucket[$__rate_interval])) by (le, messaging_destination, net_peer_name, otel_status_code)) ",
     "legendFormat": "settlement {{net_peer_name}}/{{messaging_destination}} - {{otel_status_code}}"
    }
   ]
  },
  {
   "title": "Settlement call and seqNo update rate by disposition status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_destination, messaging_servicebus_disposition_status, otel_status_code) (rate(messaging_servicebus_settlement_request_duration_count[$__rate_interval]))",
     "legendFormat": "settlement rate - {{net_peer_name}}/{{messaging_destination}} - {{messaging_servicebus_disposition_status}} - {{otel_status_code}}"
    },
    {
     "expr": "sum by (net_peer_name, messaging_destination, messaging_servicebus_disposition_status) (irate(messaging_servicebus_settlement_sequence_number[1m])) != 0",
     "legendFormat": "seqNo update - {{net_peer_name}}/{{messaging_destination}} - {{messaging_servicebus_disposition_status}}"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 } },
  {
   "title": "Management operations,  rpm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_destination, amqp_operation, amqp_status_code) (rate(messaging_az_amqp_management_request_duration_count[$__rate_interval]))",
     "legendFormat": "{{net_peer_name}}/{{messaging_destination}} - {{amqp_operation}} - {{amqp_status_code}}"
    }
   ]
  },
  {
   "title": "Credit request and prefetch rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_destination) (rate(messaging_az_amqp_consumer_credits_requested_total[$__rate_interval]))",
     "legendFormat": "credits - {{net_peer_name}}/{{messaging_destination}}"
    },
    {
     "expr": "sum by (net_peer_name,messaging_destination) (irate(messaging_az_amqp_prefetch_sequence_number[1m]))",
     "legendFormat": "prefetch - {{net_peer_name}}/{{messaging_destination}}"
    }
   ]
  }
 ]
}