{
 "title": "Azure Event Hubs SDK for Java",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sent and received event rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_destination) (rate(messaging_eventhubs_events_sent_total[$__rate_interval]))",
     "legendFormat": "sent to {{net_peer_name}}/{{messaging_destination}}"
    },
    {
     "expr": "sum by (net_peer_name, messaging_destination) (rate(messaging_eventhubs_consumer_lag_count[$__rate_interval]))",
     "legendFormat": "received from {{net_peer_name}}/{{messaging_destination}}"
    }
   ]
  },
  {
   "title": "Consumer lag per partition, P95, sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_eventhubs_consumer_lag_bucket[$__rate_interval])) by (le, messaging_destination, messaging_eventhubs_partition_id, net_peer_name)) ",
     "legendFormat": "{{net_peer_name}}/{{messaging_destination}} - partition[{{messaging_eventhubs_partition_id}}]"
    }
   ]
  },
  {
   "title": "Error rate  per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_destination, amqp_delivery_state) (rate(messaging_az_amqp_producer_send_duration_count{amqp_delivery_state!=\"accepted\"}[$__rate_interval]))",
     "legendFormat": "send {{net_peer_name}}/{{messaging_destination}} - {{amqp_delivery_state}}"
    },
    {
     "expr": "sum by (net_peer_name, messaging_destination, amqp_status_code) (rate(messaging_az_amqp_management_request_duration_count{amqp_status_code!=\"accepted\",amqp_status_code!=\"ok\"}[$__rate_interval]))",
     "legendFormat": "management {{net_peer_name}}/{{messaging_destination}} -- {{amqp_status_code}}"
    },
    {
     "expr": "sum by (net_peer_name, amqp_error_condition) (rate(messaging_az_amqp_client_link_errors_total[$__rate_interval]))",
     "legendFormat": "links {{net_peer_name}} -- {{amqp_error_condition}}"
    },
    {
     "expr": "sum by (net_peer_name, amqp_error_condition) (rate(messaging_az_amqp_client_transport_errors_total[$__rate_interval]))",
     "legendFormat": "transport {{net_peer_name}} -- {{amqp_error_condition}}"
    },
    {
     "expr": "sum by (net_peer_name, amqp_error_condition) (rate(messaging_az_amqp_client_session_errors_total[$__rate_interval]))",
     "legendFormat": "session {{net_peer_name}} -- {{amqp_error_condition}}"
    }
   ]
  },
  {
   "title": "Request duration, ms, P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_az_amqp_producer_send_duration_bucket[$__rate_interval])) by (le, amqp_delivery_state, messaging_destination, net_peer_name)) ",
     "legendFormat": "send {{net_peer_name}}/{{messaging_destination}} - {{amqp_delivery_state}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_az_amqp_management_request_duration_bucket[$__rate_interval])) by (le, messaging_destination, net_peer_name, amqp_status_code)) ",
     "legendFormat": "management {{net_peer_name}}/{{messaging_destination}} - {{amqp_status_code}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_eventhubs_checkpoint_duration_bucket[$__rate_interval])) by (le, messaging_destination, net_peer_name, otel_status_code)) ",
     "legendFormat": "checkpoint {{net_peer_name}}/{{messaging_destination}} - {{otel_status_code}}"
    }
   ]
  },
  {
   "title": "Credit request rate per partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_az_entity_path) (rate(messaging_az_amqp_consumer_credits_requested_total[$__rate_interval]))",
     "legendFormat": "{{net_peer_name}} - {{messaging_az_entity_path}}"
    }
   ]
  },
  {
   "title": "Closed connections rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, amqp_error_condition) (rate(messaging_az_amqp_client_connections_closed_total[$__rate_interval]))",
     "legendFormat": "{{net_peer_name}} - {{amqp_error_condition}}"
    }
   ]
  },
  {
   "title": "Checkpoint rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (net_peer_name,messaging_eventhubs_partition_id, messaging_destination, otel_status_code) (rate(messaging_eventhubs_checkpoint_duration_count[$__rate_interval]))",
     "legendFormat": "{{net_peer_name}}/{{messaging_destination}} - partition[{{messaging_eventhubs_partition_id}}] - {{otel_status_code}}"
    }
   ]
  },
  {
   "title": "Received message rate per partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_destination, messaging_eventhubs_consumer_group, messaging_eventhubs_partition_id) (rate(messaging_eventhubs_consumer_lag_count[$__rate_interval]))",
     "legendFormat": "{{net_peer_name}}/{{messaging_destination}} - {{messaging_eventhubs_consumer_group}} - partition[{{messaging_eventhubs_partition_id}}]"
    }
   ]
  },
  {
   "title": "Prefetch and checkpointed seqNo update rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_destination, messaging_az_entity_path) (irate(messaging_az_amqp_prefetch_sequence_number[1m]))",
     "legendFormat": "prefetch - {{net_peer_name}}/{{messaging_az_entity_path}} "
    },
    {
     "expr": "sum by (net_peer_name, messaging_destination, messaging_eventhubs_partition_id) (irate(messaging_eventhubs_checkpoint_sequence_number[1m]))",
     "legendFormat": "checkpoint - {{net_peer_name}}/{{messaging_destination}} partition[{{messaging_eventhubs_partition_id}}]"
    }
   ]
  }
 ]
}